org: richik
app: trxn-status-service
service: trxn-status-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14

functions:
  celo-mainnet:
    handler: src/chains/celo-mainnet.celoTrxnStatus
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(5 minutes)

  goerli-testnet:
    handler: src/chains/goerli-testnet.goerliTrxnStatus
    timeout: 120
    reservedConcurrency: 1
    events:
      - schedule: rate(10 minutes)

  polygon-mainnet:
    handler: src/chains/polygon-mainnet.polygonTrxnStatus
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(5 minutes)

  optimism-mainnet:
    handler: src/chains/optimism-mainnet.optimismTrxnStatus
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(3 minutes)

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
